### ISSUE TITLE
Error while trying to parse appinfo.vdf

### ISSUE THREAD

**Issue by ThreeDeeJay** [Grub4K/VDFparse#2]
Apparently, there's a new VDF version
![image](https://user-images.githubusercontent.com/71472458/206826856-54ca5583-bf1d-4c43-aacc-a28c9a7fa365.png)

which causes this tool to fail with this error:
```
vdfparse --info appinfo 208650
Error while trying to parse "c:/games/steam\appcache\appinfo.vdf"
```
SteamAppInfo updated its parser accordingly: https://github.com/SteamDatabase/SteamAppInfo/commit/b1715faba87fbbc8cb56e8fe30c92ae6ed499aab
But when I tried adding the updated AppInfo.cs, I got this error in the Github actions workflow so I think the project and maybe other files have to be updated accordingly as well.
![firefox_xXUjXrECRm](https://user-images.githubusercontent.com/71472458/206826791-c75574c5-5219-43bd-997d-67c4cf17f99a.png)

**Comment by ThreeDeeJay** [comment]
Quick update: currently the new appinfo.vdf is only used when opting in for the Steam beta.
the live/main branch is still using the old version so VDFparse should still work, but that'll change whenever Steam rolls out the new VDF out of the beta branch.

**Comment by Spodi** [comment]
I tried to do a sloppy fix here: #3
The code seemed simple enough for me to read and potentially fix.
@ThreeDeeJay, I used the info you found for that.
I did a quick test and it seems to read the new format just fine, while also maintaining the abiliy to read the old format. I just have no clue how to bundle it all up into one executable 😛

**Comment by ThreeDeeJay** [comment]
It seems https://github.com/SteamDatabase/SteamAppInfo/commit/b1715faba87fbbc8cb56e8fe30c92ae6ed499aab implemented it in a way that parses both the old and new format depending on the magic sequence in the file header. Would that be possible to implement in VDFParse? 👀
Because otherwise we might need 2 separate exes (1 for each VDF version) to cover all cases (users in current live branch, users in beta branch or users in future live branch when the new VDF has been rolled out, if/whenever that happens) 🤔

**Comment by Spodi** [comment]
well, with my changes the core executable can read both just fine (according to magic byte). Core and cli are just seperated in the source (in fact, there are many more files). While in the releases this is all bundled in one executable. And that's the step I don't know how to do.
