### ISSUE TITLE
I have created a helper that validates all paths and serves full path to verified steam games.. 

### ISSUE THREAD

**Issue by ghost** [Grub4K/VDFparse#5]
I am unsure the proper channels to share or contact you directly to inform you. 
I have built a parser to your parser, per say. Taking the output provided, then: 
-reading the list of local library paths
-iterate over every game listing, pair with all library paths to find 
    -if installed
    -where installed
    -output to file/csv
I have attached a sample output and linked my repo. 
Its not done but the release works, with small issues  like fixing backwards slashes to forward slashes. 

I dont know proper etiquette  for merging/sharing releases but all credit was given to you in the readme, and if Im not following the etiquette for github im happy to amend. 
cheers
[output.txt](https://github.com/Grub4K/VDFparse/files/10252922/output.txt)
https://github.com/samfisherirl/VDF-Steam-Library-Parse-and-Validate

**Comment by Grub4K** [comment]
You can contact me through Discord (Grub4K#2417) or E-Mail (contact@grub4k.xyz).
Feel free to use my program as per the license defined (MIT).

If you want me to include these or similar features or have other questions please do let me know by reopening this issue.
