### ISSUE TITLE
Is there any way to convert the exported (and modified) JSON file back to appinfo.vdf?

### ISSUE THREAD

**Issue by gitacct5** [Grub4K/VDFparse#6]
Not sure if this is something easy to implement...

**Comment by Grub4K** [comment]
The JSON does not retain the type information (eg. color, integer type, ...). If you suggest a way of retaining that information through JSON then I can implement it.

What is your usecase, just changing existing values or adding/removing values? In the first case the type can be guessed from the type of the original value in the vdf. For adding values I have no idea on how to reliably convert values to their underlying type.

**Comment by gitacct5** [comment]
Just thinking here (not sure if it's feasible), maybe the program can output 2 paired JSON files with the same structure, one has the value, and the other has the type informaiton?

I was initially looking for a way to change app names, remove localization info, etc. I know tools like SteamEdit has similar features, but for batch-editing, JSON is way easier to read and manipulate than a binary file.

**Comment by Grub4K** [comment]
Outputting two json files seems reasonable, just remember you would have to edit both to make it work. Do you have a specific format for each data type in mind (like string values, numeric values, etc)?

I will prepare the commandline to support this with switches to read from and write to specified destinations. If you dont have specific ideas in mind allow me some time to come up with a solid solution on my own.

**Comment by gitacct5** [comment]
Don't have a data type format in mind but I'll think about it... Thank you for considering!
